### ISSUE TITLE
Weird behavior with ForeignKey models

### ISSUE THREAD

**Issue by clokep** [plumdog/django_migration_testcase#12]
I came across a weird behavior with trying to use `ForeignKey` models in migrations. I pushed a commit (https://github.com/percipient/django_migration_testcase/commit/9a3d3242e9424e09711da9d2168845e66909eb8f) that illustrates it with a failing test.

Pretty much if you have a `ForeignKey` and attempt to create a new instance of a model (after using `get_model_before` or `get_model_after`), you get strange errors about the objects not being the correct type to add as a FK.

The results of running the added tests in that commit (I only ran SQLite, I don't have PostgreSQL installed):

```
Tests for tests/test_project_sqlite_django
Creating test database for alias 'default'...
...E.F...
======================================================================
ERROR: test_migration (test_app.tests.ForeignKeyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "django_migration_testcase/tests/test_project_sqlite_django/test_app/tests.py", line 134, in test_migration
    foreign = ForeignModel(name='test_foreign', my=my)
  File "~/.virtualenvs/django_migration_testcase/lib/python2.7/site-packages/django/db/models/base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "~/.virtualenvs/django_migration_testcase/lib/python2.7/site-packages/django/db/models/fields/related.py", line 635, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "<MyModel: MyModel object>": "ForeignModel.my" must be a "MyModel" instance.

======================================================================
FAIL: test_migration_clearly (test_app.tests.ForeignKeyTest)
A clear illustration of the problem.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "django_migration_testcase/tests/test_project_sqlite_django/test_app/tests.py", line 167, in test_migration_clearly
    self.assertEqual(MyModel, MyModel2)
AssertionError: <class 'MyModel'> != <class 'MyModel'>

----------------------------------------------------------------------
Ran 9 tests in 1.449s

FAILED (failures=1, errors=1)
```

I've tried printing out additional information in `test_migration_clearly`, but as far as I can tell they *are* the same class.

I'm not 100% sure this is a bug, maybe I'm just doing something silly, but I've spent a bit of time on this and have been unable to figure it out. Any help would be appreciated!

**Comment by plumdog** [comment]
Upsetting. Looks like a bug to me. I can confirm that I get just the same failures with as you with sqlite, and with postgres. Thanks a lot for the failing tests - I'll see what I can work out!

**Comment by clokep** [comment]
Thanks! Please let me know if I can do anything to help.

**Comment by plumdog** [comment]
I've opened a PR which includes your commit with the tests, and my fix. The tests do now pass (for me locally and on travis) - if you could let me know if this fixes your issue, then I'll merge and release.
