### ISSUE TITLE
Django 2 compatibility

### ISSUE THREAD

**Issue by jrobichaud** [plumdog/django_migration_testcase#38]
When running tests with Django 2 there is an incompatibility with the new migrate command line.

It appears that `no_initial_data` is not a valid argument anymore.

```
TypeError: Unknown option(s) for migrate command: no_initial_data. Valid options are: app_label, database, fake, fake_initial, help, interactive, migration_name, no_color, no_input, pythonpath, run_syncdb, settings, skip_checks, stderr, stdout, traceback, verbosity, version.
```

The source
```python
    def migrate_kwargs(self):
        return {'verbosity': 0,
                'no_initial_data': True, # <=== THIS CAUSES THE ERROR
                'interactive': False}

    def migrate(self, app_name, version, fake=False):
        kwargs = self.migrate_kwargs()
        kwargs['fake'] = fake
        # For Django 1.7 - does a len() check on args.
        if version:
            args = ('migrate', app_name, version)
        else:
            args = ('migrate', app_name)
        call_command(*args, **kwargs)  # <=== CRASHES HERE
```

What do you recommend to fix the issue?

I do not find anything about `no_initial_data` in the documentation of django 1.7 to 2.0.

Do you remember why it was added?

Not sure what to do about this since there is nothing about this in [django upgrade guide](https://docs.djangoproject.com/en/2.0/releases/2.0/).

What should we do:
-Remove it?
-Add condition to add it only prior to 2.0?

**Comment by clokep** [comment]
Maybe #37 fixes this?

**Comment by jrobichaud** [comment]
It will.

**Comment by jrobichaud** [comment]
I looked if there was any issues about this but I did not think about looking for any PR. My bad.

**Comment by jrobichaud** [comment]
#39 #34 fixed this.
