### ISSUE TITLE
Consolidating test apps

### ISSUE THREAD

**Issue by kaidokert** [plumdog/django_migration_testcase#5]
I just came across this - thanks for the good work.

I think you can easily combine test_app_south and test_app for a little DRYer code, because all new versions of south actually start looking for the migrations in 'south_migrations' directory first. That allows you to maintain the same django package with both South migrations and django 1.7+ migrations.

See http://south.readthedocs.org/en/latest/releasenotes/1.0.html 'Library migration path'

**Comment by plumdog** [comment]
Hi - thanks for this idea. I've opened a PR to make this change. If you could look it over and check it looks about right, that'd be brilliant.

**Comment by plumdog** [comment]
I've merged that PR because I'm about to dive into some more tweaks to the test migrations. Let me know if there's anything I've missed.
